from django.db import models
from django.conf import settings


class Theme(models.Model):
    roomEscape = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    enterKey = models.CharField(max_length=50)
    theme_number = models.PositiveIntegerField(null=True, blank=True)
    hintCount = models.PositiveIntegerField(default=3)
    name = models.CharField(max_length=30)
    hint1 = models.FileField(upload_to='mp3/', blank=True, null=True)
    sub_hint1 = models.FileField(upload_to='mp3/', blank=True, null=True)
    hint2 = models.FileField(upload_to='mp3/', blank=True, null=True)
    sub_hint2 = models.FileField(upload_to='mp3/', blank=True, null=True)
    hint3 = models.FileField(upload_to='mp3/', blank=True, null=True)
    sub_hint3 = models.FileField(upload_to='mp3/', blank=True, null=True)
    hint4 = models.FileField(upload_to='mp3/', blank=True, null=True)
    sub_hint4 = models.FileField(upload_to='mp3/', blank=True, null=True)
    hint5 = models.FileField(upload_to='mp3/', blank=True, null=True)
    sub_hint5 = models.FileField(upload_to='mp3/', blank=True, null=True)
    hint6 = models.FileField(upload_to='mp3/', blank=True, null=True)
    sub_hint6 = models.FileField(upload_to='mp3/', blank=True, null=True)
    hint7 = models.FileField(upload_to='mp3/', blank=True, null=True)
    sub_hint7 = models.FileField(upload_to='mp3/', blank=True, null=True)
    hint8 = models.FileField(upload_to='mp3/', blank=True, null=True)
    sub_hint8 = models.FileField(upload_to='mp3/', blank=True, null=True)
    hint9 = models.FileField(upload_to='mp3/', blank=True, null=True)
    sub_hint9 = models.FileField(upload_to='mp3/', blank=True, null=True)
    hint10 = models.FileField(upload_to='mp3/', blank=True, null=True)
    sub_hint10 = models.FileField(upload_to='mp3/', blank=True, null=True)
    hint11 = models.FileField(upload_to='mp3/', blank=True, null=True)
    sub_hint11 = models.FileField(upload_to='mp3/', blank=True, null=True)
    hint12 = models.FileField(upload_to='mp3/', blank=True, null=True)
    sub_hint12 = models.FileField(upload_to='mp3/', blank=True, null=True)
    hint13 = models.FileField(upload_to='mp3/', blank=True, null=True)
    sub_hint13 = models.FileField(upload_to='mp3/', blank=True, null=True)
    hint14 = models.FileField(upload_to='mp3/', blank=True, null=True)
    sub_hint14 = models.FileField(upload_to='mp3/', blank=True, null=True)
    hint15 = models.FileField(upload_to='mp3/', blank=True, null=True)
    sub_hint15 = models.FileField(upload_to='mp3/', blank=True, null=True)
    hint16 = models.FileField(upload_to='mp3/', blank=True, null=True)
    sub_hint16 = models.FileField(upload_to='mp3/', blank=True, null=True)
    hint17 = models.FileField(upload_to='mp3/', blank=True, null=True)
    sub_hint17 = models.FileField(upload_to='mp3/', blank=True, null=True)
    hint18 = models.FileField(upload_to='mp3/', blank=True, null=True)
    sub_hint18 = models.FileField(upload_to='mp3/', blank=True, null=True)
    hint19 = models.FileField(upload_to='mp3/', blank=True, null=True)
    sub_hint19 = models.FileField(upload_to='mp3/', blank=True, null=True)
    hint20 = models.FileField(upload_to='mp3/', blank=True, null=True)
    sub_hint20 = models.FileField(upload_to='mp3/', blank=True, null=True)
    hint21 = models.FileField(upload_to='mp3/', blank=True, null=True)
    sub_hint21 = models.FileField(upload_to='mp3/', blank=True, null=True)
    hint22 = models.FileField(upload_to='mp3/', blank=True, null=True)
    sub_hint22 = models.FileField(upload_to='mp3/', blank=True, null=True)
    hint23 = models.FileField(upload_to='mp3/', blank=True, null=True)
    sub_hint23 = models.FileField(upload_to='mp3/', blank=True, null=True)
    hint24 = models.FileField(upload_to='mp3/', blank=True, null=True)
    sub_hint24 = models.FileField(upload_to='mp3/', blank=True, null=True)
    hint25 = models.FileField(upload_to='mp3/', blank=True, null=True)
    sub_hint25 = models.FileField(upload_to='mp3/', blank=True, null=True)
    hint26 = models.FileField(upload_to='mp3/', blank=True, null=True)
    sub_hint26 = models.FileField(upload_to='mp3/', blank=True, null=True)
    hint27 = models.FileField(upload_to='mp3/', blank=True, null=True)
    sub_hint27 = models.FileField(upload_to='mp3/', blank=True, null=True)
    hint28 = models.FileField(upload_to='mp3/', blank=True, null=True)
    sub_hint28 = models.FileField(upload_to='mp3/', blank=True, null=True)
    hint29 = models.FileField(upload_to='mp3/', blank=True, null=True)
    sub_hint29 = models.FileField(upload_to='mp3/', blank=True, null=True)
    hint30 = models.FileField(upload_to='mp3/', blank=True, null=True)
    sub_hint30 = models.FileField(upload_to='mp3/', blank=True, null=True)
    interPhone_key = models.CharField(max_length=100, blank=True, null=True)
    interPhone_secret = models.CharField(max_length=100, blank=True, null=True)
    interPhone_ID = models.CharField(max_length=100, blank=True, null=True)

    def __str__(self):
        return self.name
