# Generated by Django 2.0 on 2019-06-19 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomEscape',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('admin', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hint1', models.FileField(upload_to='')),
                ('hint2', models.FileField(upload_to='')),
                ('hint3', models.FileField(upload_to='')),
                ('hint4', models.FileField(upload_to='')),
                ('hint5', models.FileField(upload_to='')),
                ('hint6', models.FileField(upload_to='')),
                ('hint7', models.FileField(upload_to='')),
                ('hint8', models.FileField(upload_to='')),
                ('hint9', models.FileField(upload_to='')),
                ('hint10', models.FileField(upload_to='')),
                ('hint11', models.FileField(upload_to='')),
                ('hint12', models.FileField(upload_to='')),
                ('hint13', models.FileField(upload_to='')),
                ('hint14', models.FileField(upload_to='')),
                ('hint15', models.FileField(upload_to='')),
                ('hint16', models.FileField(upload_to='')),
                ('hint17', models.FileField(upload_to='')),
                ('hint18', models.FileField(upload_to='')),
                ('hint19', models.FileField(upload_to='')),
                ('hint20', models.FileField(upload_to='')),
            ],
        ),
    ]
