# Generated by Django 2.0 on 2019-06-19 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hint', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='roomEscape',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='hint.RoomEscape'),
            preserve_default=False,
        ),
    ]
