# Generated by Django 2.0 on 2019-06-19 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hint', '0004_auto_20190619_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomescape',
            name='password',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theme',
            name='hintCount',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
