# Generated by Django 2.0 on 2019-06-20 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hint', '0005_auto_20190620_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomescape',
            name='reset',
            field=models.CharField(default=7285, max_length=20),
            preserve_default=False,
        ),
    ]
