# Generated by Django 2.0 on 2019-06-24 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hint', '0007_auto_20190621_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='theme_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
