# Generated by Django 2.0 on 2019-06-29 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hint', '0008_theme_theme_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='hint10_1',
            field=models.FileField(blank=True, null=True, upload_to='mp3/auth.User'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint11_1',
            field=models.FileField(blank=True, null=True, upload_to='mp3/auth.User'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint12_1',
            field=models.FileField(blank=True, null=True, upload_to='mp3/auth.User'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint13_1',
            field=models.FileField(blank=True, null=True, upload_to='mp3/auth.User'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint14_1',
            field=models.FileField(blank=True, null=True, upload_to='mp3/auth.User'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint15_1',
            field=models.FileField(blank=True, null=True, upload_to='mp3/auth.User'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint16_1',
            field=models.FileField(blank=True, null=True, upload_to='mp3/auth.User'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint17_1',
            field=models.FileField(blank=True, null=True, upload_to='mp3/auth.User'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint18_1',
            field=models.FileField(blank=True, null=True, upload_to='mp3/auth.User'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint19_1',
            field=models.FileField(blank=True, null=True, upload_to='mp3/auth.User'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint1_1',
            field=models.FileField(blank=True, null=True, upload_to='mp3/auth.User'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint20_1',
            field=models.FileField(blank=True, null=True, upload_to='mp3/auth.User'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint2_1',
            field=models.FileField(blank=True, null=True, upload_to='mp3/auth.User'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint3_1',
            field=models.FileField(blank=True, null=True, upload_to='mp3/auth.User'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint4_1',
            field=models.FileField(blank=True, null=True, upload_to='mp3/auth.User'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint5_1',
            field=models.FileField(blank=True, null=True, upload_to='mp3/auth.User'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint6_1',
            field=models.FileField(blank=True, null=True, upload_to='mp3/auth.User'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint7_1',
            field=models.FileField(blank=True, null=True, upload_to='mp3/auth.User'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint8_1',
            field=models.FileField(blank=True, null=True, upload_to='mp3/auth.User'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint9_1',
            field=models.FileField(blank=True, null=True, upload_to='mp3/auth.User'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='hint1',
            field=models.FileField(blank=True, null=True, upload_to='mp3/auth.User'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='hint10',
            field=models.FileField(blank=True, null=True, upload_to='mp3/auth.User'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='hint11',
            field=models.FileField(blank=True, null=True, upload_to='mp3/auth.User'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='hint12',
            field=models.FileField(blank=True, null=True, upload_to='mp3/auth.User'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='hint13',
            field=models.FileField(blank=True, null=True, upload_to='mp3/auth.User'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='hint14',
            field=models.FileField(blank=True, null=True, upload_to='mp3/auth.User'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='hint15',
            field=models.FileField(blank=True, null=True, upload_to='mp3/auth.User'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='hint16',
            field=models.FileField(blank=True, null=True, upload_to='mp3/auth.User'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='hint17',
            field=models.FileField(blank=True, null=True, upload_to='mp3/auth.User'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='hint18',
            field=models.FileField(blank=True, null=True, upload_to='mp3/auth.User'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='hint19',
            field=models.FileField(blank=True, null=True, upload_to='mp3/auth.User'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='hint2',
            field=models.FileField(blank=True, null=True, upload_to='mp3/auth.User'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='hint20',
            field=models.FileField(blank=True, null=True, upload_to='mp3/auth.User'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='hint3',
            field=models.FileField(blank=True, null=True, upload_to='mp3/auth.User'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='hint4',
            field=models.FileField(blank=True, null=True, upload_to='mp3/auth.User'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='hint5',
            field=models.FileField(blank=True, null=True, upload_to='mp3/auth.User'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='hint6',
            field=models.FileField(blank=True, null=True, upload_to='mp3/auth.User'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='hint7',
            field=models.FileField(blank=True, null=True, upload_to='mp3/auth.User'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='hint8',
            field=models.FileField(blank=True, null=True, upload_to='mp3/auth.User'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='hint9',
            field=models.FileField(blank=True, null=True, upload_to='mp3/auth.User'),
        ),
    ]
