# Generated by Django 2.0 on 2019-06-29 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hint', '0009_auto_20190629_1306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='theme',
            old_name='hint10_1',
            new_name='sub_hint1',
        ),
        migrations.RenameField(
            model_name='theme',
            old_name='hint11_1',
            new_name='sub_hint10',
        ),
        migrations.RenameField(
            model_name='theme',
            old_name='hint12_1',
            new_name='sub_hint11',
        ),
        migrations.RenameField(
            model_name='theme',
            old_name='hint13_1',
            new_name='sub_hint12',
        ),
        migrations.RenameField(
            model_name='theme',
            old_name='hint14_1',
            new_name='sub_hint13',
        ),
        migrations.RenameField(
            model_name='theme',
            old_name='hint15_1',
            new_name='sub_hint14',
        ),
        migrations.RenameField(
            model_name='theme',
            old_name='hint16_1',
            new_name='sub_hint15',
        ),
        migrations.RenameField(
            model_name='theme',
            old_name='hint17_1',
            new_name='sub_hint16',
        ),
        migrations.RenameField(
            model_name='theme',
            old_name='hint18_1',
            new_name='sub_hint17',
        ),
        migrations.RenameField(
            model_name='theme',
            old_name='hint19_1',
            new_name='sub_hint18',
        ),
        migrations.RenameField(
            model_name='theme',
            old_name='hint1_1',
            new_name='sub_hint19',
        ),
        migrations.RenameField(
            model_name='theme',
            old_name='hint20_1',
            new_name='sub_hint2',
        ),
        migrations.RenameField(
            model_name='theme',
            old_name='hint2_1',
            new_name='sub_hint20',
        ),
        migrations.RenameField(
            model_name='theme',
            old_name='hint3_1',
            new_name='sub_hint3',
        ),
        migrations.RenameField(
            model_name='theme',
            old_name='hint4_1',
            new_name='sub_hint4',
        ),
        migrations.RenameField(
            model_name='theme',
            old_name='hint5_1',
            new_name='sub_hint5',
        ),
        migrations.RenameField(
            model_name='theme',
            old_name='hint6_1',
            new_name='sub_hint6',
        ),
        migrations.RenameField(
            model_name='theme',
            old_name='hint7_1',
            new_name='sub_hint7',
        ),
        migrations.RenameField(
            model_name='theme',
            old_name='hint8_1',
            new_name='sub_hint8',
        ),
        migrations.RenameField(
            model_name='theme',
            old_name='hint9_1',
            new_name='sub_hint9',
        ),
    ]
