# Generated by Django 2.0 on 2019-08-01 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hint', '0013_auto_20190713_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='hint21',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint22',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint23',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint24',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint25',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint26',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint27',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint28',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint29',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint30',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint21',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint22',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint23',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint24',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint25',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint26',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint27',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint28',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint29',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint30',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
    ]
