# Generated by Django 2.0 on 2019-09-06 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hint', '0015_theme_enterkey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='interPhone_ID',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='interPhone_key',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='interPhone_secret',
        ),
    ]
