# Generated by Django 2.1 on 2019-10-07 03:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hint', '0018_auto_20191002_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='textHint1',
            field=ckeditor.fields.RichTextField(default=''),
            preserve_default=False,
        ),
    ]
