# Generated by Django 2.1 on 2019-11-19 05:18

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hint', '0020_auto_20191024_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='hint31',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint32',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint33',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint34',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint35',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint36',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint37',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint38',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint39',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint40',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint41',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint42',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint43',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint44',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint45',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint46',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint47',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint48',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint49',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint50',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint51',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint52',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint53',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint54',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint55',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint56',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint57',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint58',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint59',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint60',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint61',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint62',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint63',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint64',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint65',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint66',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint67',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint68',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint69',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint70',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint31',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint32',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint33',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint34',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint35',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint36',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint37',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint38',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint39',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint40',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint41',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint42',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint43',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint44',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint45',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint46',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint47',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint48',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint49',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint50',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint51',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint52',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint53',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint54',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint55',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint56',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint57',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint58',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint59',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint60',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint61',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint62',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint63',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint64',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint65',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint66',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint67',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint68',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint69',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint70',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint31',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint32',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint33',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint34',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint35',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint36',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint37',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint38',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint39',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint40',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint41',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint42',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint43',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint44',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint45',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint46',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint47',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint48',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint49',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint50',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint51',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint52',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint53',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint54',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint55',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint56',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint57',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint58',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint59',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint60',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint61',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint62',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint63',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint64',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint65',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint66',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint67',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint68',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint69',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint70',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint31',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint32',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint33',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint34',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint35',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint36',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint37',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint38',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint39',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint40',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint41',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint42',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint43',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint44',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint45',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint46',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint47',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint48',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint49',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint50',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint51',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint52',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint53',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint54',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint55',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint56',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint57',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint58',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint59',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint60',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint61',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint62',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint63',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint64',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint65',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint66',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint67',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint68',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint69',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint70',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
