# Generated by Django 2.0 on 2019-11-19 05:20

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hint', '0021_auto_20191119_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='hint71',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint72',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint73',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint74',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint75',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint76',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint77',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint78',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint79',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='hint80',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint71',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint72',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint73',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint74',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint75',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint76',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint77',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint78',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint79',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_hint80',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint71',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint72',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint73',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint74',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint75',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint76',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint77',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint78',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint79',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='sub_textHint80',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint71',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint72',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint73',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint74',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint75',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint76',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint77',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint78',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint79',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='textHint80',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
