# Generated by Django 2.0 on 2019-11-19 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hint', '0023_auto_20191119_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='enterKey',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
