# Generated by Django 2.0 on 2019-11-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hint', '0024_auto_20191119_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='enterKey',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='theme',
            name='hintCount',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='theme',
            name='name',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
