# Generated by Django 2.0 on 2019-11-22 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hint', '0025_auto_20191120_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='currentCount',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='currentHint',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
