# Generated by Django 2.0 on 2019-11-22 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hint', '0026_auto_20191122_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='currentHint',
            field=models.TextField(default='[]'),
        ),
    ]
