# Generated by Django 2.0 on 2019-11-22 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hint', '0027_auto_20191122_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='currentHint',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
