# Generated by Django 2.0 on 2019-11-22 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hint', '0028_auto_20191122_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='theme_number',
        ),
    ]
