# Generated by Django 2.0 on 2019-12-10 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hint', '0030_theme_manyhint'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='timer',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
