# Generated by Django 2.0 on 2019-12-11 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hint', '0032_auto_20191210_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='interPhone_ID',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='interPhone_key',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='interPhone_secret',
        ),
    ]
