# Generated by Django 2.0 on 2019-07-08 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190621_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nation',
            field=models.CharField(blank=True, choices=[('Korea', 'Korea'), ('Japan', 'Japan'), ('China', 'China')], max_length=30, null=True),
        ),
    ]
