# Generated by Django 2.0 on 2019-07-12 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_profile_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='interPhone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='interPhone_call1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='interPhone_call2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='interPhone_call3',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
