# Generated by Django 2.0 on 2019-07-12 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20190713_0057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='interPhone_call1',
            new_name='interPhone_call',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='interPhone_call2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='interPhone_call3',
        ),
    ]
