# Generated by Django 2.0 on 2019-08-01 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20190713_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hintCode',
            field=models.BooleanField(default=False),
        ),
    ]
