# Generated by Django 2.1 on 2019-10-08 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profile_hintcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='textHint',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hintCode',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='interPhone',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
