# Generated by Django 2.0 on 2019-11-22 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20191008_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='answer',
            field=models.BooleanField(default=False),
        ),
    ]
