# Generated by Django 2.0 on 2019-11-22 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_profile_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='hintCode',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='interPhone',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='interPhone_call',
        ),
    ]
