# Generated by Django 2.0 on 2019-11-22 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20191122_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='textHint',
            field=models.BooleanField(default=True),
        ),
    ]
