# Generated by Django 2.0 on 2019-12-03 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20191123_0228'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='money',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
