# Generated by Django 2.0 on 2019-12-10 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_profile_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='timer',
            field=models.BooleanField(default=False),
        ),
    ]
