# Generated by Django 2.0 on 2019-12-11 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_profile_timer'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pause',
            field=models.BooleanField(default=False),
        ),
    ]
