# Generated by Django 2.0 on 2020-02-05 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_profile_pause'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='onlyCode',
            field=models.BooleanField(default=False),
        ),
    ]
